/*
 *  problem_2.c
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not 
 exceed four million, find the sum of the even-valued terms. *
 */

#include <stdio.h>

int fib(int n)
{
  if(n == 0 || n == 1) return 1;
  else return fib(n-2)+fib(n-1);
}

int main(int argc, char** argv)
{		
  if(argc==2){
    int sum = 0, thisfib = 0;
    int limit = atoi(argv[1]);
    int i;
    printf("Limit: %d\n",limit);
    for(i = 0; thisfib<limit; ++i){
      thisfib = fib(i);	 
      printf("index %d fib %d\n",i,thisfib);
      if(thisfib%2==0)
	sum+=thisfib;
    }	
    printf("Sum of even fibs: %d\n", sum);
  } else {
    printf("Usage: %s limit\n", argv[0]);
  }	
  return 0;
}

